### ISSUE TITLE
Support 'OfferCreate' transaction type for packages/hw-app-xrp

### ISSUE THREAD

**Issue by whaus7** [LedgerHQ/app-xrp#2]
Right now SignTransaction only supports 'Payment' transaction types for XRP. Hoping to add support for at least 'OfferCreate' transaction types.  Seems like the second most important one after payments. I started working on this but I suppose I should see if anyone is already working on this. Or letting me know how hard it would be?

This is definitely out of my comfort zone so if anyone has any docs they could point me to so I could understand where to even begin

https://developers.ripple.com/transaction-types.html

**Comment by whaus7** [comment]
Struggling to even know where to begin on this. Is there a hardware wallet emulator or test environment to work with? Trying to just figure out how to make some changes and test them on the device

**Comment by whaus7** [comment]
Anyone know if this in the pipeline for not so distant future? Would love to know if its possibly something that's already in progress. Thanks!

**Comment by btchip** [comment]
Fixed in v2 app
