### ISSUE TITLE
Support 'TrustSet' transaction type

### ISSUE THREAD

**Issue by ghost** [LedgerHQ/app-xrp#3]
The Ledger XRP app currently supports nothing but payment transactions. Which promotes insecure practices such as entering ones mnemonic words in third-party tools, in order to sign trust line transactions.

In other words, Ledger Nano S/Nano/Blue users currently have no secure way to participate in XRP ledger airdrops and trade on the XRP ledger's decentralized exchange.

References:
https://developers.ripple.com/transaction-types.html
https://developers.ripple.com/trustset.html

**Comment by whaus7** [comment]
Yes! I'm desperate for support for 'OfferCreate' transaction types. Building out an interface for trading on the XRP ledger and hit a huge brick wall. Figured it would be simple and just assumed any transaction type would be supported ;(

**Comment by btchip** [comment]
Fixed in v2 app
