### ISSUE TITLE
Ripple Destination Tags Creation on LedgerNano or Ledger Blue

### ISSUE THREAD

**Issue by nitinjags** [LedgerHQ/app-xrp#5]
Hello,
I'm looking to find a way to create destination tags for accepting ripple in my account for Ledger Nano and Ledger Blue.

I tried to google and read the documents on ledger website but could not find the way to do it. Can you please help me over here to help me with the procedure to enable this option and create destination tags.

Thank you in advance for your support.

**Comment by RareData** [comment]
Destination tags are only relevant when sending XRP to exchanges or other XRP services. XRP sent to your own hardware wallet's account address will be under your control, no matter what destination tag you use.

**Comment by btchip** [comment]
Fixed in v2 app
